name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    permissions:
      contents: write
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: "patch"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create Release
        id: create_release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version=$(jq -r .version package.json)
          mv ./script ./LiveRemote
          zip -r "LiveRemote-${version}.zip" ./LiveRemote
          gh release create "v${version}" "LiveRemote-${version}.zip" --title "Release ${version}" --notes "This is the release for version ${version}. Check it out!"
